import { PERMISSIONS } from "./permission"

export enum Role {
  ADMIN = "ADMIN",
  CONTABILIDAD = "CONTABILIDAD",
  CONSULTA = "CONSULTA",
}

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  ADMIN: [
    PERMISSIONS.ACTIVO_READ_ANY,
    PERMISSIONS.ACTIVO_CREATE_ANY,
    PERMISSIONS.ACTIVO_UPDATE_ANY,
    PERMISSIONS.ACTIVO_DELETE_ANY,

    PERMISSIONS.USUARIO_CREATE_ANY,
    PERMISSIONS.USUARIO_DELETE_ANY,
    PERMISSIONS.USUARIO_READ_ANY,
    PERMISSIONS.USUARIO_UPDATE_ANY,

    PERMISSIONS.UBICACION_CREATE_ANY,
    PERMISSIONS.UBICACION_DELETE_ANY,
    PERMISSIONS.UBICACION_READ_ANY,
    PERMISSIONS.UBICACION_UPDATE_ANY,

    PERMISSIONS.CATEGORIA_CREATE_ANY,
    PERMISSIONS.CATEGORIA_DELETE_ANY,
    PERMISSIONS.CATEGORIA_READ_ANY,
    PERMISSIONS.CATEGORIA_UPDATE_ANY,

    PERMISSIONS.MANTENIMIENTO_CREATE_ANY,
    PERMISSIONS.TRANSFERENCIA_CREATE_ANY,
    PERMISSIONS.REPORTE_READ_ANY,

    PERMISSIONS.DEPARTAMENTO_CREATE_ANY,
    PERMISSIONS.DEPARTAMENTO_DELETE_ANY,
    PERMISSIONS.DEPARTAMENTO_UPDATE_ANY,
    PERMISSIONS.DEPARTAMENTO_READ_ANY
  ],

  CONTABILIDAD: [
    PERMISSIONS.ACTIVO_READ_OWN,
    PERMISSIONS.ACTIVO_CREATE_OWN,
    PERMISSIONS.ACTIVO_UPDATE_OWN,
    PERMISSIONS.ACTIVO_DELETE_OWN,

    PERMISSIONS.TRANSFERENCIA_CREATE_OWN,
    PERMISSIONS.MANTENIMIENTO_CREATE_OWN,

    PERMISSIONS.REPORTE_READ_OWN,
  ],

  CONSULTA: [
    PERMISSIONS.ACTIVO_READ_OWN,
    PERMISSIONS.REPORTE_READ_OWN
  ],
}

export function getUserPermissions(role: Role) {
  return ROLE_PERMISSIONS[role] || []
}

export function hasPermission(role: Role | string, permission: string) {
  return getUserPermissions(role).includes(permission)
}